#ifndef VARIAVEIS_GLOBAIS_H_INCLUDED
#define VARIAVEIS_GLOBAIS_H_INCLUDED

//Constates utilizadas pelo programa

#define LARGURA 1200
#define ALTURA 800
#define CELULAMATRIZ 50
#define MAXMONSTROS 10
#define FPS 60
#define ALTURABARRASTATUS 60
#define TAMANHOTEXTO 100
#define MAXIMODEBALAS 5
#define MAXIMODEFENOS 4

#endif // VARIAVEIS_GLOBAIS_H_INCLUDED
